#!/usr/bin/env python
"""
Extract a bibtex entry of an arXiv paper
"""

from __future__ import print_function, with_statement
from grab import find_arXiv_bib
# from bibtexparser.bparser import BibTexParser


if __name__ == "__main__":
    import sys
    if len(sys.argv) <= 1:
        print("Usage: %s <arXiv-url>" % sys.argv[0], file=sys.stderr)
        exit(1)
    bib = find_arXiv_bib(sys.argv[1])
    print(bib)
    # bp = BibTexParser(bib)
    # entry = bp.get_entry_list()[0]

