#!/usr/bin/env python
"""
Extract a bibtex entry of an arXiv paper
"""

from __future__ import print_function, with_statement
import sys
from grab import *
from bibtexparser.bparser import BibTexParser
from bibtexparser import dumps

def tex2utf8(s):
    s = s.replace('{\\\"o}', 'ö')
    s = s.replace('{\\\"a}', 'ä')
    s = s.replace('{\\\"u}', 'ü')
    return s

def utf82e(s):
    s = s.replace('ö', 'oe')
    s = s.replace('ä', 'ae')
    s = s.replace('ü', 'ue')
    s = s.replace('ß', 'ss')
    return s


if len(sys.argv) <= 1:
    print("Usage: %s <spring-url>" % sys.argv[0], file=sys.stderr)
    exit(1)

xml = getxml(sys.argv[1])

pdfurl  = findx(xml, "//x:meta[@name = 'citation_pdf_url']/@content")[0]
biburl  = findx(xml, "//x:a[contains(text(), 'BibTeX (.BIB)')]/@href")[0]
bibtex = readurl(biburl).decode('utf-8').replace("﻿", "")

bp = BibTexParser(bibtex)
entry = bp.get_entry_list()[0]

entry.pop("abstract", None)
entry.pop("url", None)
entry["pdf"] = pdfurl
entry["author"] = tex2utf8(entry["author"])

print(dumps(bp))
